export enum API_TAGS {
  USER = "USER",
  AUTH = "AUTH",
  BAKERY = "BAKERY",
  CLIENTS = "CLIENTS",
  DEBT_CLIENTS = "DEBT_CLIENTS",
  DASTAVCHIK_SAVDO = "DASTAVCHIK_SAVDO",
  ORDER = "ORDER",
  Upload = "Upload",
  COMPLAINTS = "COMPLAINTS",
}
